from __future__ import annotations

import json
from typing import Any

from app.prompts.base import PromptTemplate
from app.prompts.language_policy import chinese_primary_policy_block

LLM_REASON_PROMPT_NAME = "llm_reason_tool_prompt"
LLM_REASON_PROMPT_VERSION = "v1"
TEXT_GENERATE_PROMPT_NAME = "text_generate_tool_prompt"
TEXT_GENERATE_PROMPT_VERSION = "v1"
RAG_SEARCH_INTENT_PROMPT_NAME = "rag_search_intent_prompt"
RAG_SEARCH_INTENT_PROMPT_VERSION = "v6"
RAG_BATCH_SUMMARY_PROMPT_NAME = "rag_batch_summary_tool_prompt"
RAG_BATCH_SUMMARY_PROMPT_VERSION = "v1"
RAG_EVIDENCE_EXTRACTION_PROMPT_NAME = "rag_evidence_extraction_prompt"
RAG_EVIDENCE_EXTRACTION_PROMPT_VERSION = "v1"
RAG_ANSWER_PROMPT_NAME = "rag_answer_tool_prompt"
RAG_ANSWER_PROMPT_VERSION = "v1"


def get_llm_reason_prompt_template() -> PromptTemplate:
    return PromptTemplate(
        name=LLM_REASON_PROMPT_NAME,
        version=LLM_REASON_PROMPT_VERSION,
        description="Structured reasoning prompt for analysis tasks.",
        system_template=(
            chinese_primary_policy_block(role="你是 runtime reasoning tool。")
            + "\n"
            "请仔细分析任务，产出结构化、可执行、可落地的结果。\n"
            "如果 Additional Context 包含 Runtime Time Context，回答当前日期/时间问题时必须以它为准；use it as authoritative for current date/time questions.\n"
            "只返回 required function call。"
        ),
        user_template=(
            "Task Prompt:\n"
            "{prompt}\n\n"
            "Additional Context:\n"
            "{context_block}\n\n"
            "Return the final answer using the required structured function call."
        ),
    )


def get_text_generate_prompt_template() -> PromptTemplate:
    return PromptTemplate(
        name=TEXT_GENERATE_PROMPT_NAME,
        version=TEXT_GENERATE_PROMPT_VERSION,
        description="Structured generation prompt for final text output.",
        system_template=(
            chinese_primary_policy_block(role="你是 text generation tool。")
            + "\n"
            "请严格遵循请求，生成清晰、高质量、适合中文用户阅读的文本。\n"
            "如果 Additional Context 包含 Runtime Time Context，回答当前日期/时间问题时必须以它为准；use it as authoritative for current date/time questions.\n"
            "只返回 required function call。"
        ),
        user_template=(
            "Task Prompt:\n"
            "{prompt}\n\n"
            "Style:\n"
            "{style}\n\n"
            "Audience:\n"
            "{audience}\n\n"
            "Additional Context:\n"
            "{context_block}\n\n"
            "Return the final answer using the required structured function call."
        ),
    )


def get_rag_search_intent_prompt_template() -> PromptTemplate:
    return PromptTemplate(
        name=RAG_SEARCH_INTENT_PROMPT_NAME,
        version=RAG_SEARCH_INTENT_PROMPT_VERSION,
        description="Extract structured search intent before RAG retrieval.",
        system_template=(
            chinese_primary_policy_block(role="你是 RAG search intent extraction tool。")
            + "\n"
            "只抽取查询公司知识库前需要的搜索参数。\n"
            "不要回答用户问题，不要编造 document ids、file names、folder paths 或 scope names。\n"
            "只返回 required function call。"
        ),
        user_template=(
            "User Question:\n"
            "\n"
            "{raw_query}\n"
            "\n"
            "Allowed source_type values:\n"
            "\n"
            "pdf, word, ppt, excel, or null\n"
            "\n"
            "Goal:\n"
            "\n"
            "Extract the user's retrieval intent as faithfully as possible.\n"
            "\n"
            "Return the extracted intent using the required structured function call.\n"
            "\n"
            "Do not summarize, generalize, broaden, reinterpret, optimize, improve, or expand the user's request.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Query Editing Principle\n"
            "\n"
            "The query should be created by minimally editing the user's original question.\n"
            "\n"
            "Remove only:\n"
            "\n"
            "1. explicit document names assigned to doc_id\n"
            "\n"
            "2. explicit folder paths assigned to relative_path or absolute_path\n"
            "\n"
            "3. explicit file type words assigned to source_type\n"
            "\n"
            "4. connector words that only link a document reference to the task, such as:\n"
            "\n"
            "中\n"
            "里的\n"
            "在…中\n"
            "在…里面\n"
            "关于\n"
            "\n"
            "Only remove these words when they connect a document reference to the task.\n"
            "\n"
            "Do not remove them when they are part of the task meaning.\n"
            "\n"
            "Prefer preserving more original wording rather than less.\n"
            "\n"
            "Do not rewrite user wording into synonyms.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Preserve User Intent\n"
            "\n"
            "Always preserve:\n"
            "\n"
            "- task objective\n"
            "- action words\n"
            "- grouping dimensions\n"
            "- comparison targets\n"
            "- filtering conditions\n"
            "- time expressions\n"
            "- judgment criteria\n"
            "\n"
            "Examples of important concepts:\n"
            "\n"
            "每个人\n"
            "每个日期\n"
            "每个部门\n"
            "本周工作\n"
            "下周计划\n"
            "负责人\n"
            "状态\n"
            "完成情况\n"
            "是否完成\n"
            "未完成事项\n"
            "异常情况\n"
            "冲突\n"
            "重复\n"
            "缺失\n"
            "\n"
            "Do not remove these concepts when they appear in the user request.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Action Preservation\n"
            "\n"
            "Always preserve user actions.\n"
            "\n"
            "Examples:\n"
            "\n"
            "比较\n"
            "对比\n"
            "判断\n"
            "查找\n"
            "提取\n"
            "统计\n"
            "汇总\n"
            "分析\n"
            "核对\n"
            "识别\n"
            "找出\n"
            "筛选\n"
            "排序\n"
            "列出\n"
            "归纳\n"
            "\n"
            "Do not remove action words.\n"
            "\n"
            "Do not convert action-oriented requests into noun phrases.\n"
            "\n"
            "Bad:\n"
            "\n"
            "找出未完成事项\n"
            "\n"
            "↓\n"
            "\n"
            "未完成事项\n"
            "\n"
            "Good:\n"
            "\n"
            "找出未完成事项\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Business Completion Tracking Handling\n"
            "\n"
            "If the user is asking about weekly reports, next-week plans, department plans, monthly plans, 三七计划, completion status, completion tracking, task closure, completion rate, or execution status:\n"
            "\n"
            "Preserve the objective exactly when this RAG tool is already being used, but do not turn the request into a full-document spreadsheet analysis objective.\n"
            "\n"
            "These business tracking requests are normally handled by MySQL business tools outside RAG. The search intent extractor must not add broader RAG objectives for them.\n"
            "\n"
            "Never convert it into:\n"
            "\n"
            "- generic data analysis\n"
            "- generic data comparison\n"
            "- generic statistics\n"
            "- document summary\n"
            "- date-range comparison\n"
            "- whole-spreadsheet analysis\n"
            "- full document chunk retrieval\n"
            "\n"
            "Examples of completion-tracking concepts:\n"
            "\n"
            "是否完成\n"
            "完成情况\n"
            "哪些已完成\n"
            "哪些未完成\n"
            "工作项是否闭环\n"
            "任务是否落实\n"
            "本周工作是否在下周计划中完成\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Forbidden Transformations\n"
            "\n"
            "Never replace a specific task with a generic task.\n"
            "\n"
            "Forbidden replacements include:\n"
            "\n"
            "分析数据\n"
            "查看数据\n"
            "查看文件\n"
            "查询资料\n"
            "处理表格\n"
            "内容分析\n"
            "信息提取\n"
            "数据对比\n"
            "数据统计\n"
            "文件查询\n"
            "文档分析\n"
            "文档总结\n"
            "内容总结\n"
            "\n"
            "unless the user explicitly used those words.\n"
            "\n"
            "Bad:\n"
            "\n"
            "比较每个人本周工作和下周计划\n"
            "\n"
            "↓\n"
            "\n"
            "数据对比\n"
            "\n"
            "Bad:\n"
            "\n"
            "统计每个日期销售额\n"
            "\n"
            "↓\n"
            "\n"
            "数据统计\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Spreadsheet Rules\n"
            "\n"
            "For Excel or table-related questions:\n"
            "\n"
            "Preserve exactly:\n"
            "\n"
            "- grouping dimensions\n"
            "- comparison targets\n"
            "- metrics\n"
            "- time expressions\n"
            "- judgment criteria\n"
            "\n"
            "Do not collapse multiple dimensions into a generic summary.\n"
            "\n"
            "Do not replace metrics with broader concepts.\n"
            "\n"
            "Keep the original analytical objective unchanged.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Document Reference Handling\n"
            "\n"
            "When a document reference exists:\n"
            "\n"
            "Move the document reference into doc_id.\n"
            "\n"
            "Remove only the document reference itself from query.\n"
            "\n"
            "Keep the task objective unchanged.\n"
            "\n"
            "If removing the document reference would make the query unclear, preserve more of the original wording.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "DocID Extraction\n"
            "\n"
            "Extract doc_id only when the user clearly refers to a specific document.\n"
            "\n"
            "Priority:\n"
            "\n"
            "1. filename with extension\n"
            "\n"
            "2. filename without extension\n"
            "\n"
            "3. document title\n"
            "\n"
            "4. document scope\n"
            "\n"
            "Preserve original wording exactly.\n"
            "\n"
            "Do not normalize document names.\n"
            "\n"
            "Do not shorten document names.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Folder Path Extraction\n"
            "\n"
            "If the user clearly provides a folder, directory, or path, extract the exact path.\n"
            "\n"
            "Use absolute_path when the path starts with /, \\, a drive path such as C:\\path, or a NAS root such as 9goo-nas/.\n"
            "\n"
            "Use relative_path for non-absolute folder paths such as 项目A/合同.\n"
            "\n"
            "Do not put folder paths into doc_id.\n"
            "\n"
            "If no explicit folder path is provided, use null for both path fields.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Source Type Extraction\n"
            "\n"
            "Infer source_type only from explicit file type indicators.\n"
            "\n"
            "Mapping:\n"
            "\n"
            "doc\n"
            "docx\n"
            "word\n"
            "→ word\n"
            "\n"
            "pdf\n"
            "→ pdf\n"
            "\n"
            "ppt\n"
            "pptx\n"
            "→ ppt\n"
            "\n"
            "xls\n"
            "xlsx\n"
            "excel\n"
            "→ excel\n"
            "\n"
            "Otherwise:\n"
            "\n"
            "source_type = null\n"
            "\n"
            "Do not infer source_type from document content.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Confidence\n"
            "\n"
            "high\n"
            "\n"
            "All extracted fields are explicit.\n"
            "\n"
            "medium\n"
            "\n"
            "Some fields require minor inference.\n"
            "\n"
            "low\n"
            "\n"
            "The request is ambiguous.\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Example 1\n"
            "\n"
            "User:\n"
            "\n"
            "统计销售明细.xlsx中每个日期的销售额\n"
            "\n"
            "Output:\n"
            "\n"
            "{{\n"
            "  \"query\": \"统计每个日期的销售额\",\n"
            "  \"source_type\": \"excel\",\n"
            "  \"doc_id\": \"销售明细.xlsx\",\n"
            "  \"confidence\": \"high\"\n"
            "}}\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Example 2\n"
            "\n"
            "User:\n"
            "\n"
            "技术宝典.docx里的安全内容有哪些\n"
            "\n"
            "Output:\n"
            "\n"
            "{{\n"
            "  \"query\": \"安全内容有哪些\",\n"
            "  \"source_type\": \"word\",\n"
            "  \"doc_id\": \"技术宝典.docx\",\n"
            "  \"confidence\": \"high\"\n"
            "}}\n"
            "\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "\n"
            "Final Validation\n"
            "\n"
            "Before returning the result, verify:\n"
            "\n"
            "1. Action words are preserved.\n"
            "\n"
            "2. Comparison targets are preserved.\n"
            "\n"
            "3. Grouping dimensions are preserved.\n"
            "\n"
            "4. Time expressions are preserved.\n"
            "\n"
            "5. Completion-tracking objectives are preserved.\n"
            "\n"
            "6. No new objectives were introduced.\n"
            "\n"
            "7. No new date ranges were introduced.\n"
            "\n"
            "8. No new filters were introduced.\n"
            "\n"
            "9. The query remains as close as possible to the user's original request.\n"
            "\n"
            "If any important concept from the original request is missing, revise the extraction before returning the final result.\n"
        ),
    )


def get_rag_batch_summary_prompt_template() -> PromptTemplate:
    return PromptTemplate(
        name=RAG_BATCH_SUMMARY_PROMPT_NAME,
        version=RAG_BATCH_SUMMARY_PROMPT_VERSION,
        description="Summarize a single RAG batch for downstream final generation.",
        system_template=(
            chinese_primary_policy_block(role="你是 RAG batch summarization tool。")
            + "\n"
            "只总结当前提供的 batch，不要跨 batch 推断。\n"
            "不得编造事实。\n"
            "只返回 strict JSON。"
        ),
        user_template=(
            "User Question:\n"
            "{query}\n\n"
            "Batch ID:\n"
            "{batch_id}\n\n"
            "Batch Content:\n"
            "{batch_content}\n\n"
            "Return JSON with keys: text, summary, key_points, evidence_chunk_ids."
        ),
    )


def get_rag_evidence_extraction_prompt_template() -> PromptTemplate:
    return PromptTemplate(
        name=RAG_EVIDENCE_EXTRACTION_PROMPT_NAME,
        version=RAG_EVIDENCE_EXTRACTION_PROMPT_VERSION,
        description="Query-focused evidence extraction prompt for RAG batches.",
        system_template=(
            chinese_primary_policy_block(role="你是 query-focused RAG evidence extraction tool。")
            + "\n"
            "只抽取与用户 query 相关的证据。\n"
            "原文存在数字、日期、条件、限制和流程顺序时，必须精确保留。\n"
            "evidence_chunk_ids 和 irrelevant_chunk_ids 只能使用输入提供的 chunk_ids 或 source_chunk_ids。\n"
            "如果上下文不足，把缺失信息写入 missing_information。\n"
            "不得编造事实，不得使用外部知识或常识补全。\n"
            "只返回 strict JSON with keys: answer_facts, key_points, evidence_chunk_ids, irrelevant_chunk_ids, missing_information, records, confidence.\n"
            "records 仅用于保存用户问题直接需要的结构化事实，不要做跨周完成率、计划追踪或落地复盘判断。confidence must be one of: high, medium, low."
        ),
        user_template=(
            "Batch Input JSON:\n"
            "{batch_input_json}\n\n"
            "Extract query-focused evidence from this batch. Return strict JSON only."
        ),
    )


def get_rag_answer_prompt_template() -> PromptTemplate:
    return PromptTemplate(
        name=RAG_ANSWER_PROMPT_NAME,
        version=RAG_ANSWER_PROMPT_VERSION,
        description="Grounded RAG answer prompt for final text output.",
        system_template=(
            chinese_primary_policy_block(role="你是一个严格基于检索证据回答问题的助手。")
            + "\n"
            "你只能使用 Additional Context 中的信息回答。\n"
            "如果上下文没有明确证据，必须说明“当前检索结果不足以回答”。\n"
            "如果 Additional Context 中包含 Raw Evidence Context，即使 Evidence Extraction JSON 解析失败，也必须优先基于 Raw Evidence Context 回答。\n"
            "不要把“模型未返回有效证据提取 JSON”理解为“没有检索到数据”。\n"
            "JSON 解析失败只代表中间抽取失败，不代表原始资料不存在。\n"
            "如果 Raw Evidence Context 中包含数字、日期、表名、科目名称，应直接使用这些证据回答。\n"
            "不得因为 missing_information 中出现“JSON 解析失败”就回答“没有数据”。\n"
            "不得使用常识补全。不得编造。\n"
            "必须保留原文中的数字、日期、条件、限制和流程顺序。\n"
            "如果有 chunk_id，回答中尽量标注来源。\n"
            "Return the final answer using the required structured function call."
        ),
        user_template=(
            "User Question:\n"
            "{user_question}\n\n"
            "Additional Context:\n"
            "{context_block}\n\n"
            "Instructions:\n"
            "只能基于 Additional Context 回答。证据不足必须说明“当前检索结果不足以回答”。\n"
            "如果 Additional Context 中包含 Raw Evidence Context，即使 Evidence Extraction JSON 解析失败，也必须优先基于 Raw Evidence Context 回答。\n"
            "不要把“模型未返回有效证据提取 JSON”或“JSON 解析失败”理解为没有检索到数据。\n"
            "JSON 解析失败只代表中间抽取失败，不代表原始资料不存在；不得因此回答没有数据。\n"
            "如果 Raw Evidence Context 中包含数字、日期、表名、科目名称，应直接使用这些证据回答。\n"
            "不得使用常识补全，不得编造。必须保留数字、日期、条件、限制和流程顺序。\n"
            "如果有 chunk_id，回答中尽量标注来源。\n\n"
            "Return the final answer using the required structured function call."
        ),
    )
